export const arrEndpoint = [
  'http://localhost:3000/json-793',
  // 'http://localhost:3000/json-744493',
  // 'http://localhost:3000/json-955',
  // 'http://localhost:3000/json-231',
  // 'http://localhost:3000/json-931',
  // 'http://localhost:3000/json-93',
  // 'http://localhost:3000/json-342',
];

// export const arrEndpoint = [
//   'https://jsonbase.com/sls-team/json-793',
//   'https://jsonbase.com/sls-team/json-955',
//   'https://jsonbase.com/sls-team/json-231',
//   'https://jsonbase.com/sls-team/json-931',
//   'https://jsonbase.com/sls-team/json-93',
//   'https://jsonbase.com/sls-team/json-342',
//   'https://jsonbase.com/sls-team/json-770',
//   'https://jsonbase.com/sls-team/json-491',
//   'https://jsonbase.com/sls-team/json-281',
//   'https://jsonbase.com/sls-team/json-718',
//   'https://jsonbase.com/sls-team/json-310',
//   'https://jsonbase.com/sls-team/json-806',
//   'https://jsonbase.com/sls-team/json-469',
//   'https://jsonbase.com/sls-team/json-258',
//   'https://jsonbase.com/sls-team/json-516',
//   'https://jsonbase.com/sls-team/json-79',
//   'https://jsonbase.com/sls-team/json-706',
//   'https://jsonbase.com/sls-team/json-521',
//   'https://jsonbase.com/sls-team/json-350',
//   'https://jsonbase.com/sls-team/json-64',
// ];
